import { useCallback, useEffect, useRef, useState } from "react";
import { API_URL } from "../api";
import { socket } from "../socket";
import "./ElderConnect.css";

const copy = {
  "en-IN": { title:"Elder Connect", back:"Back", find:"Find an Elder", code:"Patient Code", search:"Search", send:"Send Connection Request", requests:"Connection Requests", connections:"My Elder Connections", accept:"Accept", reject:"Reject", noneRequests:"No connection requests", noneConnections:"No elder connections yet", connected:"Connected", call:"Audio Call", calling:"Calling…", incoming:"Incoming Call", acceptCall:"Accept Call", rejectCall:"Reject Call", mute:"Mute", unmute:"Unmute", end:"End Call", ended:"Call Ended", failed:"Unable to connect the call.", connecting:"Connecting…", inCall:"Connected", offline:"Audio calling requires an internet connection.", close:"Close", age:"Age", language:"Language", remove:"Remove" },
  "hi-IN": { title:"वरिष्ठ संपर्क", back:"वापस", find:"किसी वरिष्ठ को खोजें", code:"रोगी कोड", search:"खोजें", send:"कनेक्शन अनुरोध भेजें", requests:"कनेक्शन अनुरोध", connections:"मेरे वरिष्ठ संपर्क", accept:"स्वीकार करें", reject:"अस्वीकार करें", noneRequests:"कोई कनेक्शन अनुरोध नहीं", noneConnections:"अभी कोई वरिष्ठ संपर्क नहीं", connected:"जुड़े हुए", call:"ऑडियो कॉल", calling:"कॉल हो रही है…", incoming:"आने वाली कॉल", acceptCall:"कॉल स्वीकार करें", rejectCall:"कॉल अस्वीकार करें", mute:"म्यूट", unmute:"अनम्यूट", end:"कॉल समाप्त करें", ended:"कॉल समाप्त हुई", failed:"कॉल कनेक्ट नहीं हो सकी।", connecting:"कनेक्ट हो रहा है…", inCall:"कनेक्टेड", offline:"ऑडियो कॉल के लिए इंटरनेट चाहिए।", close:"बंद करें", age:"आयु", language:"भाषा", remove:"हटाएं" },
  "te-IN": { title:"వృద్ధుల అనుసంధానం", back:"వెనుకకు", find:"వృద్ధుడిని కనుగొనండి", code:"రోగి కోడ్", search:"వెతకండి", send:"కనెక్షన్ అభ్యర్థన పంపండి", requests:"కనెక్షన్ అభ్యర్థనలు", connections:"నా వృద్ధుల కనెక్షన్లు", accept:"అంగీకరించండి", reject:"తిరస్కరించండి", noneRequests:"కనెక్షన్ అభ్యర్థనలు లేవు", noneConnections:"ఇంకా వృద్ధుల కనెక్షన్లు లేవు", connected:"కనెక్ట్ అయ్యారు", call:"ఆడియో కాల్", calling:"కాలింగ్…", incoming:"వచ్చే కాల్", acceptCall:"కాల్ అంగీకరించండి", rejectCall:"కాల్ తిరస్కరించండి", mute:"మ్యూట్", unmute:"అన్‌మ్యూట్", end:"కాల్ ముగించండి", ended:"కాల్ ముగిసింది", failed:"కాల్ కనెక్ట్ కాలేదు.", connecting:"కనెక్ట్ అవుతోంది…", inCall:"కనెక్ట్ అయ్యారు", offline:"ఆడియో కాల్‌కు ఇంటర్నెట్ అవసరం.", close:"మూసివేయండి", age:"వయస్సు", language:"భాష", remove:"తొలగించండి" },
  "as-IN": { title:"জ্যেষ্ঠ সংযোগ", back:"উভতি যাওক", find:"এজন জ্যেষ্ঠক বিচাৰক", code:"ৰোগী ক'ড", search:"বিচাৰক", send:"সংযোগ অনুৰোধ পঠাওক", requests:"সংযোগ অনুৰোধ", connections:"মোৰ জ্যেষ্ঠ সংযোগ", accept:"গ্ৰহণ কৰক", reject:"প্ৰত্যাখ্যান কৰক", noneRequests:"কোনো সংযোগ অনুৰোধ নাই", noneConnections:"এতিয়াও কোনো জ্যেষ্ঠ সংযোগ নাই", connected:"সংযুক্ত", call:"অডিঅ' কল", calling:"কল হৈছে…", incoming:"আহি থকা কল", acceptCall:"কল গ্ৰহণ কৰক", rejectCall:"কল প্ৰত্যাখ্যান কৰক", mute:"মিউট", unmute:"আনমিউট", end:"কল শেষ কৰক", ended:"কল শেষ হৈছে", failed:"কল সংযোগ কৰিব নোৱাৰিলে।", connecting:"সংযোগ হৈ আছে…", inCall:"সংযুক্ত", offline:"অডিঅ' কলৰ বাবে ইণ্টাৰনেট লাগে।", close:"বন্ধ কৰক", age:"বয়স", language:"ভাষা", remove:"আঁতৰাওক" },
  "bn-IN": { title:"প্রবীণ সংযোগ", back:"ফিরে যান", find:"একজন প্রবীণকে খুঁজুন", code:"রোগী কোড", search:"খুঁজুন", send:"সংযোগ অনুরোধ পাঠান", requests:"সংযোগ অনুরোধ", connections:"আমার প্রবীণ সংযোগ", accept:"গ্রহণ করুন", reject:"প্রত্যাখ্যান করুন", noneRequests:"কোনো সংযোগ অনুরোধ নেই", noneConnections:"এখনও কোনো প্রবীণ সংযোগ নেই", connected:"সংযুক্ত", call:"অডিও কল", calling:"কল হচ্ছে…", incoming:"আগত কল", acceptCall:"কল গ্রহণ করুন", rejectCall:"কল প্রত্যাখ্যান করুন", mute:"মিউট", unmute:"আনমিউট", end:"কল শেষ করুন", ended:"কল শেষ হয়েছে", failed:"কল সংযোগ করা যায়নি।", connecting:"সংযোগ হচ্ছে…", inCall:"সংযুক্ত", offline:"অডিও কলের জন্য ইন্টারনেট প্রয়োজন।", close:"বন্ধ করুন", age:"বয়স", language:"ভাষা", remove:"সরান" },
  "nag-IN": { title:"Elder Connect", back:"Ghuribo", find:"Elder bisaribo", code:"Patient Code", search:"Bisaribo", send:"Connection request pathabo", requests:"Connection Requests", connections:"Mur Elder Connections", accept:"Accept", reject:"Reject", noneRequests:"Connection request nai", noneConnections:"Elder connection nai", connected:"Connected", call:"Audio Call", calling:"Calling…", incoming:"Incoming Call", acceptCall:"Accept Call", rejectCall:"Reject Call", mute:"Mute", unmute:"Unmute", end:"End Call", ended:"Call Ended", failed:"Call connect nohoi.", connecting:"Connecting…", inCall:"Connected", offline:"Audio call karibole internet lage.", close:"Close", age:"Age", language:"Language", remove:"Remove" },
};

export default function ElderConnect({ onBack = () => {}, language = "en-IN", backgroundOnly = false }) {
  const t = copy[language] || copy["en-IN"];
  const token = localStorage.getItem("mindset_ner_token");
  const headers = { "Content-Type": "application/json", Authorization: `Bearer ${token}` };
  const [code, setCode] = useState(""); const [found, setFound] = useState(null); const [requests, setRequests] = useState([]); const [connections, setConnections] = useState([]); const [notice, setNotice] = useState("");
  const [call, setCall] = useState(null); const [muted, setMuted] = useState(false);
  const peer = useRef(null); const stream = useRef(null); const remoteAudio = useRef(null); const pendingIce = useRef([]); const callRef = useRef(null);
  useEffect(() => { callRef.current = call; }, [call]);
  const load = useCallback(async () => { try { const h = { Authorization: `Bearer ${token}` }; const [a, b] = await Promise.all([fetch(`${API_URL}/api/elder-connections/requests`, { headers: h }), fetch(`${API_URL}/api/elder-connections/connections`, { headers: h })]); const ad = await a.json(); const bd = await b.json(); if (a.ok) setRequests(ad.requests || []); if (b.ok) setConnections(bd.connections || []); } catch { setNotice(t.failed); } }, [token, t.failed]);
  useEffect(() => { load(); }, [load]);
  const ensureSocket = useCallback(() => new Promise((resolve, reject) => {
    if (socket.connected) return resolve();
    socket.auth = { token: localStorage.getItem("mindset_ner_token") };
    const timeout = window.setTimeout(() => {
      socket.off("connect", connected);
      socket.off("connect_error", failed);
      reject(new Error("Call service is unavailable."));
    }, 8000);
    const connected = () => { window.clearTimeout(timeout); socket.off("connect_error", failed); resolve(); };
    const failed = () => { window.clearTimeout(timeout); socket.off("connect", connected); reject(new Error("Call service is unavailable.")); };
    socket.once("connect", connected);
    socket.once("connect_error", failed);
    socket.connect();
  }), []);
  const emit = useCallback(async (event, payload) => {
    try {
      await ensureSocket();
      return await new Promise((resolve) => socket.timeout(8000).emit(event, payload, (error, response) => {
        resolve(error ? { ok: false, message: "Call service did not respond. Please try again." } : response);
      }));
    } catch (error) {
      return { ok: false, message: error.message || "Call service is unavailable." };
    }
  }, [ensureSocket]);
  const cleanup = useCallback((message) => { stream.current?.getTracks().forEach((track) => track.stop()); stream.current = null; peer.current?.close(); peer.current = null; pendingIce.current = []; if (remoteAudio.current) remoteAudio.current.srcObject = null; setMuted(false); const next = message ? { phase: "ended", message } : null; callRef.current = next; setCall(next); }, []);
  const makePeer = useCallback(async (targetPatientId) => { const local = await navigator.mediaDevices.getUserMedia({ audio: true, video: false }); stream.current = local; const pc = new RTCPeerConnection({ iceServers: [{ urls: "stun:stun.l.google.com:19302" }, { urls: "stun:stun1.l.google.com:19302" }] }); peer.current = pc; local.getTracks().forEach((track) => pc.addTrack(track, local)); pc.onicecandidate = ({ candidate }) => { if (candidate) emit("elder-call-ice-candidate", { targetPatientId, candidate }); }; pc.ontrack = ({ streams }) => { if (remoteAudio.current) { remoteAudio.current.srcObject = streams[0]; remoteAudio.current.play().catch((error) => console.warn("Remote call audio could not start:", error)); } }; pc.onconnectionstatechange = () => { if (pc.connectionState === "failed") cleanup(t.failed); }; return pc; }, [cleanup, t.failed]);
  useEffect(() => {
    const incoming = (data) => { const next = { phase: "incoming", targetPatientId: data.caller?.patientId, name: data.caller?.name || "Elder" }; callRef.current = next; setCall(next); };
    const accepted = async (data) => { if (callRef.current?.phase !== "calling") return; try { const next = { ...callRef.current, phase: "connecting" }; callRef.current = next; setCall(next); const pc = await makePeer(data.caller?.patientId); const offer = await pc.createOffer(); await pc.setLocalDescription(offer); await emit("elder-call-offer", { targetPatientId: data.caller?.patientId, offer }); } catch (error) { console.error("Unable to create call offer:", error); cleanup(t.failed); } };
    const rejected = () => cleanup(t.ended);
    const offer = async (data) => { try { const pc = peer.current || await makePeer(data.caller?.patientId); await pc.setRemoteDescription(new RTCSessionDescription(data.offer)); for (const candidate of pendingIce.current) await pc.addIceCandidate(candidate); pendingIce.current = []; const answer = await pc.createAnswer(); await pc.setLocalDescription(answer); await emit("elder-call-answer", { targetPatientId: data.caller?.patientId, answer }); setCall((v) => ({ ...v, phase: "connected" })); } catch { cleanup(t.failed); } };
    const answer = async (data) => { if (peer.current && data.answer) { await peer.current.setRemoteDescription(new RTCSessionDescription(data.answer)); for (const candidate of pendingIce.current) await peer.current.addIceCandidate(candidate); pendingIce.current = []; setCall((v) => ({ ...v, phase: "connected" })); } };
    const ice = async (data) => { const candidate = new RTCIceCandidate(data.candidate); if (peer.current?.remoteDescription) await peer.current.addIceCandidate(candidate); else pendingIce.current.push(candidate); };
    const ended = () => cleanup(t.ended); const refresh = () => load();
    socket.on("elder-call-request", incoming); socket.on("elder-call-accepted", accepted); socket.on("elder-call-rejected", rejected); socket.on("elder-call-offer", offer); socket.on("elder-call-answer", answer); socket.on("elder-call-ice-candidate", ice); socket.on("elder-call-ended", ended); socket.on("elder-connection-request", refresh); socket.on("elder-connection-accepted", refresh);
    return () => { ["elder-call-request", "elder-call-accepted", "elder-call-rejected", "elder-call-offer", "elder-call-answer", "elder-call-ice-candidate", "elder-call-ended", "elder-connection-request", "elder-connection-accepted"].forEach((event) => socket.off(event)); cleanup(); };
  }, [cleanup, emit, load, makePeer, t.ended, t.failed]);
  const request = async () => { const res = await fetch(`${API_URL}/api/elder-connections/request`, { method: "POST", headers, body: JSON.stringify({ patientCode: found.patientCode }) }); const data = await res.json(); setNotice(data.message); if (res.ok) setFound(null); };
  const search = async () => { const res = await fetch(`${API_URL}/api/elder-connections/search/${encodeURIComponent(code)}`, { headers: { Authorization: `Bearer ${token}` } }); const data = await res.json(); setFound(res.ok ? data.patient : null); setNotice(res.ok ? (data.connectionStatus === "accepted" ? "Already connected" : data.connectionStatus === "pending" ? "Request already pending" : "") : data.message); };
  const decide = async (id, action) => { const res = await fetch(`${API_URL}/api/elder-connections/${id}/${action}`, { method: "PUT", headers }); const data = await res.json(); setNotice(data.message); if (res.ok) load(); };
  const start = async (person) => { if (!navigator.onLine) return setNotice(t.offline); const targetPatientId = String(person.id || person._id); const next = { phase: "calling", targetPatientId, name: person.name }; callRef.current = next; setCall(next); const result = await emit("elder-call-request", { targetPatientId }); if (!result?.ok) cleanup(result?.message || t.failed); };
  const acceptCall = async () => { const result = await emit("elder-call-accepted", { targetPatientId: call.targetPatientId }); if (!result?.ok) cleanup(result?.message || t.failed); else { const next = { ...callRef.current, phase: "connecting" }; callRef.current = next; setCall(next); } };
  const end = async () => { if (call?.targetPatientId) await emit("elder-call-ended", { targetPatientId: call.targetPatientId }); cleanup(t.ended); };
  const toggleMute = () => { stream.current?.getAudioTracks().forEach((track) => { track.enabled = muted; }); setMuted((v) => !v); };
  return <main className="elder-connect-page"><audio ref={remoteAudio} autoPlay /><button className="elder-back" onClick={onBack}>← {t.back}</button><h1>🤝 {t.title}</h1>{notice && <p className="elder-notice">{notice}</p>}<section className="elder-card"><h2>{t.find}</h2><div className="elder-search"><input value={code} onChange={(e) => setCode(e.target.value)} placeholder={t.code} aria-label={t.code} /><button onClick={search}>{t.search}</button></div>{found && <div className="elder-person"><strong>{found.name}</strong><span>{t.age}: {found.age} · {t.language}: {found.language}</span><span>{t.code}: {found.patientCode}</span><button onClick={request}>{t.send}</button></div>}</section><section className="elder-card"><h2>{t.requests}</h2>{requests.length ? requests.map((row) => <div className="elder-person" key={row.id}><strong>{row.patient.name}</strong><span>{t.age}: {row.patient.age} · {row.patient.language}</span><div><button onClick={() => decide(row.id, "accept")}>{t.accept}</button><button className="elder-secondary" onClick={() => decide(row.id, "reject")}>{t.reject}</button></div></div>) : <p>{t.noneRequests}</p>}</section><section className="elder-card"><h2>{t.connections}</h2>{connections.length ? connections.map((row) => <div className="elder-person" key={row.id}><strong>{row.patient.name}</strong><span>{t.age}: {row.patient.age} · {row.patient.language}</span><b>{t.connected}</b><button className="elder-call-button" onClick={() => start(row.patient)}>📞 {t.call}</button></div>) : <p>{t.noneConnections}</p>}</section>{call && <div className="elder-call-overlay" role="dialog" aria-modal="true"><div className="elder-call-dialog"><h2>{call.phase === "incoming" ? t.incoming : call.phase === "calling" ? t.calling : call.phase === "connecting" ? t.connecting : call.phase === "connected" ? t.inCall : call.message || t.ended}</h2>{call.phase !== "ended" && <p>{call.name}</p>}{call.phase === "incoming" && <div><button onClick={acceptCall}>{t.acceptCall}</button><button className="elder-secondary" onClick={() => { emit("elder-call-rejected", { targetPatientId: call.targetPatientId }); cleanup(t.ended); }}>{t.rejectCall}</button></div>}{["calling", "connecting", "connected"].includes(call.phase) && <div>{call.phase === "connected" && <button onClick={toggleMute}>{muted ? `🔊 ${t.unmute}` : `🎙 ${t.mute}`}</button>}<button className="elder-end" onClick={end}>☎ {t.end}</button></div>}{call.phase === "ended" && <button onClick={() => cleanup()}>{t.close}</button>}</div></div>}</main>;
}
